language: python
python:
- '3.5'
install: pip install -r requirements.txt
services:
- postgresql
before_script:
- psql -c 'create database landavailability_test;' -U postgres
- psql -U postgres -c "create extension postgis"
- cd landavailability
env:
  global:
  - LANDAVAILABILITY_DB_NAME="landavailability_test"
  - LANDAVAILABILITY_DB_USER="postgres"
  - LANDAVAILABILITY_DB_PASSWORD=""
  - LANDAVAILABILITY_DB_HOST=localhost
  - LANDAVAILABILITY_DB_PORT=5432
  - SECRET_KEY="abcd1234"
script: pytest -v
deploy:
  provider: heroku
  buildpack: https://github.com/cyberdelia/heroku-geo-buildpack.git
  api_key:
    secure: mYjbq6TevNxImVQFNNW8QHj8sc7NNZnZ0lkwVIxPvRFWaGmCfmOwfD7/pMD6FYga75zWhmpdGFWerwnucOENc1RRSuESQFMXY01KaNllqjBAJFexkThO/1jFlRk7BW1vkQ5y0/lS8fIJ2WdI3UzzQ2RWpexMfm532H145RgKn2NutCWp6NBpKBYVYxKjO9y6d4B3+OeVUYWOsToPm+WjoyuHWVjwAhat7JGTjt8WTlnwv7x/3BSQSPh5z0t2pNXgizJMyBARf0iMZjQnUnkM2cxsypd3mjPfLFz+ViLQsSkRHd5Vxsgviq/pKFDTB/1ecUhpgyORxRabGonxUthljMe3Um78+YjTYy4EON4+iHWEgofEdaFA86A4DUs05hl9+kWVwgSyxTxBwUiRKbwnkiFb8VbwS2eqT+eSYAdPCt3yb4RBf3kRc6zkMhH+IzDGrE0jjYhofCuKaYF5ZMstVqpKCfIypQnJfH94SY5NeUbghenPutjPCv5U9EVYEG4iQyYgHTr1Y43wawmr7PjwB5xCbWl6FmnzPnm9cOTNeBUiGbz7Vcjo1szw8BMWOlqB2t1MuiFUFJO40LERNGOw+GabOj2zsu3JKf05u/0Q52hOCaChXWbgDPZ0iKnlHm2Pol1uIBgTBGJKLkYas5mmkhJYDFbPBK1sxjvd7t5qCVM=
  app: land-availability-api
  on:
    repo: alphagov/land-availability-api
  run:
    - "python landavailability/manage.py migrate"
