language: python
python:
  - '3.5'
  - '3.6'
install: pip install -r requirements.txt
addons:
  postgresql: 9.5
  apt:
    packages:
    - postgresql-9.5-postgis-2.3
before_script:
- psql -c 'create database landavailability_test;' -U postgres
- psql -U postgres -c "create extension postgis"
- cd landavailability
env:
  global:
  - SECRET_KEY="abcd1234"
  - DATABASE_URL=postgres://postgres@localhost:5432/landavailability_test
script: pytest -v --cov-report= --cov=api tests/
after_success: coveralls
deploy:
  provider: heroku
  buildpack: https://github.com/cyberdelia/heroku-geo-buildpack.git
  api_key:
    secure: "Ek73pJSgNyZhM+6TB6w7tIPMDDZQj4nGfWVjf+Npveqzu4HOdVgWOTuSYkR78+1cH3ZAYEUyH/g0HWodmaTnn4rtEVHPjpPMJhMYiS0NFsI+gROfO4/kBUIIBh9HzdGhHdrN2SH3w7lurh7KscgUbmROoo9W8Kr0PBEfxLQiZygVtW5ynAXlE5vicN3KPJ8LxhzM3EAYCfUWbreNXYFXBYf/mkrciUusnOOf1fBH9oZh+JOqa8OH6tKXrSd/A3gQUtZNRmNnTdjh6GDJtI4DT4Z3iHRNwp8CQ3f5Xx1ie2PfpD19q2KR47iNI4vtPCi7hAaYlvjZmzppwsqBbPBZwKM9Q9gYFLeBKTN3GnxZwFls1Sgkey8X1HIcTfKYUqWznrpA8MIBMUi64YRwzJX4PCzBrTmi6R/X0pzq8Leaxc9vyB7ko2lmyZbFfi4UJYDbg8fNMNLSLsTaq1a2etP2Zp3+rJh51WC89QXAa3m58OOPKN2PbzNZDew6gV+RbC5HqPLartPf+/dX+3aSNvGq3VuNZd8TPRTqBkqyR4CiWt0Hpx6DyVFPq2ycvSzPsuPbDg1Dq8ShKoI4vmSNhRitp2YjsAdtkKhv8U/wx3hb5blHsA/UrNsM6LmXmGHlRj2oueo8k3QepuZsdfbPYn6zcakcqKTPulJkYAK8WKsq4RM="
  strategy: git
  app: land-availability-api
  on:
    repo: alphagov/land-availability-api
  run:
    - "python landavailability/manage.py migrate"
