# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 13:31
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_codepoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amic_code', models.CharField(db_index=True, max_length=20)),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('direction', models.CharField(blank=True, max_length=255, null=True)),
                ('area', models.CharField(blank=True, max_length=20, null=True)),
                ('road', models.CharField(blank=True, max_length=255, null=True)),
                ('nptg_code', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
