# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 10:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_trainstop'),
        ('api', '0003_busstop'),
    ]

    operations = [
    ]
