# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20161130_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='nearest_busstop_distance',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='nearest_trainstop_distance',
            field=models.FloatField(null=True),
        ),
    ]
