# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 11:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20161130_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='nearest_busstop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.BusStop'),
        ),
        migrations.AlterField(
            model_name='location',
            name='nearest_trainstop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.TrainStop'),
        ),
    ]
