# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 11:49
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20161206_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Substation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('operating', models.CharField(blank=True, max_length=255, null=True)),
                ('action_dtt', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('owner_flag', models.CharField(blank=True, max_length=255, null=True)),
                ('gdo_gid', models.CharField(blank=True, max_length=255, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(geography=True, srid=4326)),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='nearest_substation_distance',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='nearest_substation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Substation'),
        ),
    ]
