# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 13:00
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20161212_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverheadLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gdo_gid', models.CharField(db_index=True, max_length=255)),
                ('route_asset', models.CharField(blank=True, max_length=255, null=True)),
                ('towers', models.CharField(blank=True, max_length=255, null=True)),
                ('action_dtt', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('operating', models.CharField(blank=True, max_length=255, null=True)),
                ('circuit_1', models.CharField(blank=True, max_length=255, null=True)),
                ('circuit_2', models.CharField(blank=True, max_length=255, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(geography=True, srid=4326)),
            ],
        ),
    ]
