# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 13:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_overheadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='nearest_ohl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.OverheadLine'),
        ),
        migrations.AddField(
            model_name='location',
            name='nearest_ohl_distance',
            field=models.FloatField(null=True),
        ),
    ]
