# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 09:41
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20161213_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overheadline',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryField(geography=True, srid=4326),
        ),
    ]
