# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 10:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_motorway'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='nearest_motorway',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Motorway'),
        ),
        migrations.AddField(
            model_name='location',
            name='nearest_motorway_distance',
            field=models.FloatField(null=True),
        ),
    ]
