# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-16 12:07
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20161215_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broadband',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postcode', models.CharField(db_index=True, max_length=255)),
                ('point', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('speed_30_mb_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('min_download_speed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('avg_download_speed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_download_speed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('min_upload_speed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('avg_upload_speed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_upload_speed', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
