# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-16 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_broadband'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='nearest_broadband',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Broadband'),
        ),
        migrations.AddField(
            model_name='location',
            name='nearest_broadband_distance',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='nearest_broadband_fast',
            field=models.NullBooleanField(),
        ),
    ]
