# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 15:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_greenbelt'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE api_greenbelt ALTER COLUMN geom TYPE geography(MultiPolygonZ, 4326);")
    ]
