# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-20 10:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20161219_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='nearest_greenbelt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Greenbelt'),
        ),
        migrations.AddField(
            model_name='location',
            name='nearest_greenbelt_distance',
            field=models.FloatField(null=True),
        ),
    ]
