# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-21 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='nearest_school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.School'),
        ),
        migrations.AddField(
            model_name='location',
            name='nearest_school_distance',
            field=models.FloatField(null=True),
        ),
    ]
