# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-22 11:44
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20161221_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetroTube',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atco_code', models.CharField(db_index=True, max_length=255)),
                ('naptan_code', models.CharField(db_index=True, max_length=255)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('locality', models.CharField(blank=True, max_length=255, null=True)),
                ('point', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
            ],
        ),
    ]
