# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-22 13:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_metrotube'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='nearest_metrotube',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.MetroTube'),
        ),
        migrations.AddField(
            model_name='location',
            name='nearest_metrotube_distance',
            field=models.FloatField(null=True),
        ),
    ]
