# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-04 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20161222_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busstop',
            name='amic_code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
