# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-09 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20170104_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainstop',
            name='atcode_code',
            field=models.CharField(max_length=24, unique=True),
        ),
    ]
