# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-10 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20170109_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='uprn',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
