# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20170110_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codepoint',
            name='postcode',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
