# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20170111_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codepoint',
            name='country',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='codepoint',
            name='county',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='codepoint',
            name='district',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='codepoint',
            name='nhs_health_authority',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='codepoint',
            name='nhs_region',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='codepoint',
            name='quality',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='codepoint',
            name='ward',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
