# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-16 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20170111_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadband',
            name='postcode',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
