# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-17 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20170116_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrotube',
            name='atco_code',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
