# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-18 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_auto_20170118_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substation',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
