# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-19 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_auto_20170119_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='urn',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
