# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-20 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_auto_20170119_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrotube',
            name='naptan_code',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
