# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-17 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_auto_20170120_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='uprn',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
