# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-09 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_auto_20170217_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='ba_ref',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
