# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-23 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_location_ba_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='full_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
