# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-29 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_location_full_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='estimated_floor_space',
            field=models.DecimalField(decimal_places=2, max_digits=16, null=True),
        ),
    ]
