# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-06 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_auto_20170516_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='nearest_greenbelt',
        ),
        migrations.RemoveField(
            model_name='location',
            name='nearest_greenbelt_distance',
        ),
        migrations.AddField(
            model_name='location',
            name='greenbelt_overlap',
            field=models.NullBooleanField(),
        ),
    ]
